### 创建用户地址信息
GET http://localhost:8099/ecommerce-goodsorder-service/orderGoods/allCartItem
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEsXCJ1c2VybmFtZVwiOlwicm9vdFwifSIsImp0aSI6IjhjZjg4MzZkLWJiZTUtNGViOS1iNTBhLWEwMzc5MmQyMjgwZCIsImV4cCI6MTY2MTAxMTIwMH0.IwgWD5O4tGqztxXrLMtq4LZ_Tya2mgGiu_SEgYQb_1vmEedCwFBJxrxaBC0Hl-0HjiXC1ISAdbi2o96QdxdjylT97LT6FwjPhpKXBawOTJ0zEX1l3G4fdYmNC5tilR-zzBip1BX5lb2gEmzb7eunhJB--Q0JPI2ZXkhcBAdhTvB0nuy7aK-iSprSRSk0Mc8qlEkiR54lwo4rb4jv8EsvzW7st_zsW6mAtr2tLLRdyyrrYUh82oXNz7l7BkZUkZVQ0SN2Vi4THppnPLHab-P1zBIZ8k645PHZw6Nk2lWxPUrf1CBbVPz-KFQZfFosnhHto5oWcGA3tvgYyYde0YScZg

{
  "userId" : null
}
