### 查询服务
GET http://127.0.0.1:9001/imooc/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEsXCJ1c2VybmFtZVwiOlwicm9vdFwifSIsImp0aSI6IjNlMzFjZDNjLThiYTgtNDY2Ny1hODI1LTc1MmRkNTAzYTg2YSIsImV4cCI6MTY1Nzk4NzIwMH0.kAa4bc5G7WJsudDTtLhW6TuJbq2egC1uH_Rwvx8g32adp-kZi3PMC_6s2T_HWr-Zo8T3T_jTpi9XhzjNyJnzhg5Gsv_1LC7CQenItWvmxyejJQfP2DG3xImByhZEa11694YIis21IV5vQJwnNWgIcpwOvHH0vqZRim7FAdt1ejtG-LwgkwPS0oouymRQRQIJ5QqXhgWXMXfHGDUorRoXhJPMngxEEGab6HUDEQPzwuXG3M1_nSJW6FRetVOj9thfqyqhI_aS5GYQ4cnc8kRc7XC30ds5Jk33zCHuyb-rHuglOibhAMN0CfSO3uIfFaullUZPEDObvZTx9wGq5w_gkQ
token: imooc
